### ISSUE TITLE
Add EPICS PV timestamp to camonitor function

### ISSUE THREAD

**Issue by marcilioc** [wanglin86769/node-epics-ca#4]
I was reading your library and I noticed you didn't include the timestamp values from EPICS camonitor function. For my use cases it is a very useful information and would be nice to have it!
I researched for it and the libca already supports EPICS timestamps and other libraries with the same purpose as yours added it as well.

Please let me know if I just missed something about it

**Comment by wanglin86769** [comment]
Thanks for raising this question, but I am sorry that due to my limited knowledge of EPICS, currently it is not easy for me to add this timestamp support.

**node-epics-ca** uses the simple DBR* types like **DBR_STRING** and **DBR_INT** to send requests to the CA server, so only the value returns from the CA server in the **dbr** field of the following structure,

typedef struct event_handler_args {
    void            *usr;  
    chanId          chid;   
    long            type;  
    long            count; 
    const void      *dbr;   
    int             status; 
} evargs;

Other libraries which can monitor the timestamp as you mentioned should have used the compound types like **DBR_TIME_STRING** and **DBR_TIME_INT** which return the value as well as timestamp.

**Comment by marcilioc** [comment]
Thanks for your answer! I see the approach is slightly different, so this suggestion may not be as useful as I thought it would be.

Even though, I appreciate your return about this. I'll close this issue, since it wont be useful for your project.
